# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CurrentPositionUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 444)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.module_list = QtWidgets.QListWidget(self.centralwidget)
        self.module_list.setGeometry(QtCore.QRect(10, 110, 231, 192))
        self.module_list.setObjectName("module_list")
        self.archive_module = QtWidgets.QPushButton(self.centralwidget)
        self.archive_module.setGeometry(QtCore.QRect(120, 50, 81, 23))
        self.archive_module.setObjectName("archive_module")
        self.select_btn = QtWidgets.QPushButton(self.centralwidget)
        self.select_btn.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.select_btn.setObjectName("select_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 50, 91, 31))
        self.label.setObjectName("label")
        self.top_positions_table = QtWidgets.QTableView(self.centralwidget)
        self.top_positions_table.setGeometry(QtCore.QRect(380, 110, 256, 192))
        self.top_positions_table.setObjectName("top_positions_table")
        self.create_position_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_position_btn.setGeometry(QtCore.QRect(370, 60, 75, 23))
        self.create_position_btn.setObjectName("create_position_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHide_Archived = QtWidgets.QAction(MainWindow)
        self.actionHide_Archived.setCheckable(True)
        self.actionHide_Archived.setObjectName("actionHide_Archived")
        self.new_mod_btn = QtWidgets.QAction(MainWindow)
        self.new_mod_btn.setObjectName("new_mod_btn")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionModule = QtWidgets.QAction(MainWindow)
        self.actionModule.setObjectName("actionModule")
        self.menuNew.addAction(self.new_mod_btn)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionHide_Archived)
        self.menuEdit.addAction(self.actionModule)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.archive_module.setText(_translate("MainWindow", "Archive Module"))
        self.select_btn.setText(_translate("MainWindow", "Select Module"))
        self.label.setText(_translate("MainWindow", "Top Positions"))
        self.create_position_btn.setText(_translate("MainWindow", "New Position"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHide_Archived.setText(_translate("MainWindow", "Hide Archived"))
        self.new_mod_btn.setText(_translate("MainWindow", "Module"))
        self.new_mod_btn.setStatusTip(_translate("MainWindow", "Add a new module"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionModule.setText(_translate("MainWindow", "Module"))
        self.actionModule.setStatusTip(_translate("MainWindow", "Edit a Module"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
