# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\newModule.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(413, 300)
        self.new_mod_confirm = QtWidgets.QPushButton(Form)
        self.new_mod_confirm.setGeometry(QtCore.QRect(120, 190, 75, 23))
        self.new_mod_confirm.setObjectName("new_mod_confirm")
        self.new_mod_cancel = QtWidgets.QPushButton(Form)
        self.new_mod_cancel.setGeometry(QtCore.QRect(220, 190, 75, 23))
        self.new_mod_cancel.setObjectName("new_mod_cancel")
        self.mod_name_input = QtWidgets.QPlainTextEdit(Form)
        self.mod_name_input.setGeometry(QtCore.QRect(40, 60, 104, 41))
        self.mod_name_input.setPlainText("")
        self.mod_name_input.setPlaceholderText("")
        self.mod_name_input.setObjectName("mod_name_input")
        self.mod_code_input = QtWidgets.QPlainTextEdit(Form)
        self.mod_code_input.setGeometry(QtCore.QRect(150, 60, 104, 41))
        self.mod_code_input.setPlainText("")
        self.mod_code_input.setObjectName("mod_code_input")
        self.mod_year_input = QtWidgets.QPlainTextEdit(Form)
        self.mod_year_input.setGeometry(QtCore.QRect(260, 60, 104, 41))
        self.mod_year_input.setPlainText("")
        self.mod_year_input.setObjectName("mod_year_input")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 30, 71, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 71, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(280, 30, 71, 20))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.new_mod_confirm.setText(_translate("Form", "Confirm"))
        self.new_mod_cancel.setText(_translate("Form", "Cancel"))
        self.label.setText(_translate("Form", "Module Code"))
        self.label_2.setText(_translate("Form", "Module Name"))
        self.label_3.setText(_translate("Form", "Module Year"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
